// <auto-generated />
namespace Danyal_Chatha_Passion_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Accoladee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Accoladee));
        
        string IMigrationMetadata.Id
        {
            get { return "202302162002499_Accoladee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
